# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - server-redzone-insights

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Set up Yarn
        run: |
          corepack enable
          yarn set version 4.2.2
          yarn config set nodeLinker node-modules

      - name: yarn install server and build
        run: |
          yarn install
          yarn run server-build
      - name: copy build output to out dir
        run: |
          mkdir -p out
          cp -r packages/server/dist out/
          cp -r node_modules out/
          cp packages/server/package.json out/
          cp yarn.lock out/

      - name: Zip artifact for deployment
        run: zip release.zip ./out/* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_510CE3ED91694AEA9BA73644D35BE220 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9E6C05BEA1794C619322558E277DF714 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_18AEBEBC26824A6797BE9FAC9DE7E270 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'server-redzone-insights'
          slot-name: 'Production'
          package: ./out
          
